# Generated by Django 5.0.6 on 2024-06-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('trainer_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('duration', models.PositiveBigIntegerField()),
                ('objective', models.CharField(max_length=100)),
                ('module', models.PositiveSmallIntegerField()),
                ('prior_needed_skills', models.CharField(max_length=20)),
                ('learning_materials', models.CharField(max_length=20)),
                ('attendance_per_week', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
