# Generated by Django 3.2.12 on 2024-06-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('building_material', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('capacity', models.PositiveBigIntegerField()),
                ('lighting', models.CharField(max_length=100)),
                ('temeprature', models.PositiveSmallIntegerField()),
                ('odor', models.CharField(max_length=20)),
                ('comfort', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
